name: Angular Build

# {1}
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.16]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      # {2}
      - name: Checkout the source code
        uses: actions/checkout@v3

      # {3}
      - name: Setup Node.js $
        uses: actions/setup-node@v3
        with:
          node-version: $
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # {4}
      - name: Install dependencies
        run: npm ci
      # {5}
      - name: Run tests
        run: npm run test:ci
      # {6}
      - name: Build
        run: npm run build

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # or ${{ github.actor }} for GitHub Packages
          password: ${{ secrets.DOCKER_PAT }} # or ${{ secrets.DOCKER_PASSWORD }} or ${{ secrets.GITHUB_TOKEN }} for GitHub Packages

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: abrhernandez/quiniela_coto_ui:${{ github.sha }} # Replace with your image name and tag
